# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user1_turn',
            field=models.BooleanField(default=True),
        ),
    ]
