# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-18 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_game_user1_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
