# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_remove_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(default='____________________________________', max_length=36),
        ),
    ]
